default:
	( cd kernel && make )
	( cd lib && make )
	( cd tests && make )
	( cd documentation && make )

install:
	( cd kernel && make install )
	( cd lib && make install )
	( cd include && make install )
	( cd documentation && make install )

clean:
	( cd kernel && make clean )
	( cd lib && make clean )
	( cd tests && make clean )
	( cd documentation && make clean )
